### ISSUE TITLE
multiplayer doesn't work

### ISSUE THREAD

**Issue by SHADOWELITE7** [sergeyt/cubeslam#7]
when I give my link to someone to play with, my friend automatically goes to the main menu rather than the game room

**Comment by itsmrTech** [comment]
+1

**Comment by SHADOWELITE7** [comment]
whats the +1 for @itsmrTech

**Comment by dylan1234312** [comment]
Hey, did you ever figure this out

**Comment by ThatAndresV** [comment]
Late to the party, but +1

**Comment by SHADOWELITE7** [comment]
@dylan1234312 I believe the dev abandoned it
that's all I can say

Singleplayer is available
multiplayer lobby code works but you can't connect. I guess its peer to peer connection

**Comment by SHADOWELITE7** [comment]
I could reopen this issue but I don't think it would be fixed
